export const EN_MESSAGE = {
  key001: "Please contact the administrator",
  key002: "No registered image\nPlease contact the administrator",
  key003: "CSV registration failed\nPlease contact the administrator",
  key004: "Failed to send mail\nPlease contact the administrator",
  key005: "Date of birth is required",
  key006: "Telephone number is required",
  key007: "Address is required",
  key008: "Zip code is required",
  key009: "Receiver is required",
  key010: "Recipient's phone number is required",
  key011: "Please enter your date of birth in 8 characters",
  key012: "Please enter only numbers for date of birth",
  key013: "Please enter only positive numbers for birth",
  key014: "Update processed successfully",
  key015: "Failed to delete",
  key016: "Send mail successfully\nPlease continue to change your password",
  key017: "Password update successfully processed",  
  key018: "Membership registration has been completed",
  key019: "Please try again later",
  key020: "Sent an email\nPlease continue with the user registration procedure",
  key021: "Email address is already registered",
  key022: "Last name is required",
  key023: "Name is required",
  key024: "Your reservation has been accepted",
  key025: "Send mail successfully",
  key026: "Email is required",
  key027: "Password is required",
  key028: "Password confirm is required",
  key029: "Email is invalid",
  key030: "Passwords do not match",
  key031: "Please enter a password of 6 characters or more",
  key032: "This product is out of stock",
  key033: "Successfully deleted",
  key034: "Please login",
  key035: "Please select an image",
  key036: "Please enter Japanese title",
  key037: "Please enter an English title",
  key038: "Please enter Chinese title",
  key039: "Please enter a Japanese product description",
  key040: "Please enter an English product description",
  key041: "Please enter a Chinese product description",
  key042: "Please enter the contents",
  key043: "Please enter only numbers for the price",
  key044: "Please check the price",
  key045: "Now on air and recording cannot be selected together",
  key046: "URL is required",
  key047: "Product is already registered",
  key048: "Failed to get product information",
  key049: "Mail setup time is in the past",
  key050: "Coupon code is already registered",
  key051: "Code is required",
  key052: "Please enter the sales code in 4 characters",
  key053: "Please enter sales type",
  key054: "Please enter only numbers for the amount",
  key055: "Please enter only positive numbers for the amount",
  key056: "If the category is ALL, you cannot designate a product",
  key057: "Please set the product in the relevant category",
  key058: "Initial amount cannot be entered for this sales type",
  key059: "Please enter only numbers for the minimum amount",
  key060: "Please enter only positive numbers for the minimum amount",
  key061: "Expiry date is required",  
  key062: "Please check the date",
  key063: "If the category is ALL, sales exclusion cannot be set",
  key064: "There are multiple same sales within the period",
  key065: "Sale registration completed",
  key066: "Duplicate sales code",
  key067: "Failed to get sale information",
  key068: "Please select active or inactive",
  key069: "Sale update successfully processed",
  key070: "Failed to get user information",
  key071: "Failed to get point information",
  key072: "Failed to get coupon information",
  key073: "Failed to get product information",
  key074: "Failed to get order information",
  key075: "There is a problem with the selected file",
  key076: "Please enter only numbers for phone number",
  key077: "Please enter the recipient's address",
  key078: "Please confirm payment status",
  key079: "Please login",
  key080: "Please enter a number",
  key081: "This product is not subject to inventory management",
  key082: "Please check stock quantity",
  key083: "The product quantity condition is valid only when it is All",
  key084: "Negative numbers cannot be used",

// 高橋
  key085: "Please enter your coupon or points",
  key086: "Please enter only numbers for points",
  key087: "Points can be used from 100 points",
  key088: "Please check the available points",
  key089: "Points can be applied only once",
  key090: "Coupon can only be used once",
  key091: "Please enter coupon",
  key092: "Birthday coupons cannot be used",
  key093: "This coupon has expired",
  key094: "This coupon cannot be used in conjunction with sales",
  key095: "The coupon redemption limit has been exceeded",  
  key096: "Failed to search coupon history information\nPlease contact your administrator",
  key097: "Failed to save file",
  key098: "Code registration successful",
  key099: "Coupon has been registered",
  key100: "Coupon has been deleted",
  key101: "Coupon has been edited", 
  key102: "Images upload was successful",
  key103: "Images deleted was successful",
  key104: "Image deletion failed",
  key105: "This coupon can only be used by designated users",
  key106: "This is an unregistered coupon",
  key107: "There are no categories or products for which coupons can be used",
  key108: "Code is required",
  key109: "Value1 is required",
  key110: "This is a registered code",
  key111: "In case of category ALL, product selection is not possible",
  key112: "Please enter the coupon code in 4 characters",
  key113: "Please enter sales type",
  key114: "Sale code is already registered",
  key115: "Please enter coupon type",
  key116: "Expiration period is required",
  key117: "Past dates cannot be used",
  key118: "Mail setup time is in the past",
  key119: "Please check the entered date",
  key120: "Please enter the count in 2 digits",
  key121: "Please enter only numbers for count",
  key122: "Please enter only positive numbers for the count",
  key123: "The same kind of coupon exists within the period",
  key124: "There are duplicate coupon codes",
  key125: "Image is required",
  key126: "Only one image can be registered\nClick on the image you want to delete to delete it",
  key127: "Images is already registered",
  key128: "Please check the quantity",
  key129: "Check out your Account or Password again",
}

export const JP_MESSAGE = {
  key001: "管理者にお問い合わせください",
  key002: "画像が登録されていません\n管理者にお問い合わせください",
  key003: "CSV登録に失敗しました\n管理者にお問い合わせください",
  key004: "メールの送信に失敗しました\n管理者にお問い合わせください",
  key005: "生年月日は必須です",
  key006: "電話番号は必須です",
  key007: "住所は必須です",
  key008: "郵便番号は必須です",
  key009: "受取人は必須です",
  key010: "受取人の電話番号は必須です",
  key011: "生年月日は8文字で入力してください",
  key012: "生年月日は数字のみ入力してください",
  key013: "生年月日は正数のみ入力してください",
  key014: "アップデートは正常に処理されました",
  key015: "削除に失敗しました",
  key016: "メールを正常に送信しました\nパスワードの変更を続けてください",
  key017: "パスワード更新が正常に処理されました",
  key018: "会員登録が完了しました",
  key019: "しばらく経ってから再度お試しください",
  key020: "メールを送信しました\n引き続きユーザー登録手続きを行ってください",
  key021: "すでに登録されているメールアドレスです",
  key022: "姓は必須です",
  key023: "名は必須です",
  key024: "ご予約を受け付けました",
  key025: "メールを正常に送信しました",
  key026: "メールアドレスは必須です",
  key027: "パスワードは必須です",
  key028: "パスワード確認は必須です",
  key029: "メールが無効です",
  key030: "パスワードが一致していません",
  key031: "パスワードは6文字以上で入力してください",
  key032: "この商品は在庫切れです",
  key033: "正常に削除されました。",
  key034: "ログインしてください",
  key035: "画像を選択してください",
  key036: "日本語の商品名を入力してください",
  key037: "英語の商品名を入力してください",
  key038: "中国語の商品名を入力してください",
  key039: "日本語の商品説明を入力してください",
  key040: "英語の商品説明を入力してください",
  key041: "中国語の商品説明を入力してください",
  key042: "コンテンツを入力してください",
  key043: "価格は数字のみを入力してください",
  key044: "価格をご確認ください",
  key045: "Now on airと録画を同時に選択することはできません",
  key046: "URLは必須です",
  key047: "製品はすでに登録されています",
  key048: "製品情報の取得に失敗しました",
  key049: "メール設定時間が過去です",
  key050: "クーポンコードはすでに登録されています",
  key051: "コードは必須です",
  key052: "セールコードは 4 文字で入力してください",
  key053: "セールタイプを入力してください",
  key054: "金額は数字のみを入力してください",
  key055: "金額は正数のみ入力してください",
  key056: "カテゴリがALLの場合、商品の指定はできません",
  key057: "当該カテゴリの商品を設定してください",
  key058: "当該販売タイプでは初期金額の入力はできません",
  key059: "最低金額は数字のみ入力してください",
  key060: "最低金額は正数のみ入力してください",
  key061: "有効期限は必須です",  
  key062: "日付をご確認ください",
  key063: "カテゴリがALLの場合、セール除外の設定はできません",
  key064: "期間内に同じセールが複数あります",
  key065: "セール登録が完了しました",
  key066: "コードが重複しています",
  key067: "セール情報の取得に失敗しました",
  key068: "アクティブまたは非アクティブを選択してください",
  key069: "セール更新が正常に処理されました",
  key070: "ユーザー情報の取得に失敗しました",
  key071: "ポイント情報の取得に失敗しました",
  key072: "クーポン情報の取得に失敗しました",
  key073: "製品情報の取得に失敗しました",
  key074: "注文情報の取得に失敗しました",
  key075: "選択したファイルに問題があります",
  key076: "電話番号は数字のみを入力してください",
  key077: "受取人の住所を入力してください",
  key078: "決済をご確認ください",
  key079: "ログインしてください",
  key080: "数字を入力してください",
  key081: "この商品は在庫管理の対象外となります",
  key082: "在庫数をご確認ください",
  key083: "商品数量条件は「ALL」の場合のみ有効です",
  key084: "負の数値は使用できません",

  key085: "クーポンまたはポイントを入力してください",
  key086: "ポイントは数字のみを入力してください",
  key087: "ポイントは100ポイントからご利用いただけます",
  key088: "利用可能なポイントを確認してください",
  key089: "ポイントの適用は1回のみとなります",
  key090: "クーポンは1回のみ使用可能です",
  key091: "クーポンを入力してください",
  key092: "誕生日クーポンは利用できません",
  key093: "有効期間が過ぎたクーポンです",
  key094: "このクーポンはセールとの併用はできません",
  key095: "クーポンの引き換え上限を超えています",
  key096: "クーポン履歴情報の検索に失敗しました\n管理者にお問い合わせください",
  key097: "ファイルの保存に失敗しました",
  key098: "コードの登録に成功しました",
  key099: "クーポンが登録されました",
  key100: "クーポンは削除されました",
  key101: "クーポンが編集されました", 
  key102: "イメージのアップロードが成功しました",
  key103: "イメージの削除は成功しました",
  key104: "イメージの削除に失敗しました",
  key105: "このクーポンは指定されたユーザーのみが使用できます",
  key106: "登録されてないクーポンです",
  key107: "クーポンが利用できるカテゴリー・商品はありません",
  key108: "コードは必須です",
  key109: "値1は必須です",
  key110: "すでに登録されているコードです",
  key111: "カテゴリALLの場合、商品選択はできません",
  key112: "クーポンコードを4文字で入力してください",
  key113: "販売タイプを入力してください",
  key114: "セールコードはすでに登録されています",
  key115: "クーポンタイプを入力してください",
  key116: "有効期限は必須です",  
  key117: "過去の日付は使えません",
  key118: "メール設定時間が過去です",
  key119: "入力した日付を確認してください",
  key120: "カウントは2桁で入力してください",
  key121: "カウントには数字のみを入力してください",
  key122: "カウントには正の数値のみを入力してください",
  key123: "期間内に同じのクーポンがあります",
  key124: "クーポンコードが重複しています",
  key125: "イメージは必須です",
  key126: "登録できるイメージは 1つだけです\n削除したいイメージをクリックして削除してください",
  key127: "すでに登録されているイメージです",
  key128: "数量をご確認ください",
  key129: "アカウントまたはパスワードを再度確認してください",
}

export const CN_MESSAGE = {
  key001: "请联系管理员",
  key002: "图像登录失败¥n请联系管理员",
  key003: "CSV 注册失败\n请联系管理员",
  key004: "发送邮件失败\n请联系管理员",
  key005: "请填写出生年月日",
  key006: "请填写电话号码",
  key007: "请填写住址",
  key008: "请填写邮编",
  key009: "请填写收件人姓名",
  key010: "请填写收件人电话号码",
  key011: "请您输入出生年月日（8位数字)",
  key012: "请输入出生日期",
  key013: "请输入有效出生年月日",
  key014: "已更新成功",
  key015: "删除失败",
  key016: "邮件发送成功¥n继续更改密码",
  key017: "最新密码设置成功",
  key018: "会员注册已完成",
  key019: "请稍后再试",
  key020: "电子邮件已发送¥n请继续完成注册内容",
  key021: "该邮箱已被注册",
  key022: "请输入姓氏",
  key023: "请输入名字",
  key024: "您的预定已成功",
  key025: "发送邮件成功",
  key026: "请输入邮箱",
  key027: "请输入密码",
  key028: "请确认密码",
  key029: "电子邮件不正确",
  key030: "密码不匹配",
  key031: "请输入至少 6 个字符的密码",
  key032: "此产品缺货",
  key033: "删除成功",
  key034: "请登录",
  key035: "请选择图片",
  key036: "请输入日文标题",
  key037: "请输入英文标题",
  key038: "请输入中文标题",
  key039: "请输入日语的产品说明",	
  key040: "请输入英文产品描述",
  key041: "请输入中文产品描述",
  key042: "请输入内容",	
  key043: "请输入数字金额",
  key044: "请确认价格",
  key045: "正在播出和录音不能同时选择",
  key046: "请输入网址",
  key047: "产品已注册",
  key048: "无法读取商品信息",
  key049: "设置邮件已超时",
  key050: "优惠劵号码已登录",
  key051: "请输入登录号码",
  key052: "请输入4位折扣码",
  key053: "请输入折扣类型",
  key054: "请输入数字金额",
  key055: "请输入正确数字金额",
  key056: "则无法指定产品",
  key057: "请将产品设置在相关类别中",
  key058: "无法为此销售类型输入初始金额",
  key059: "请输入最低金额",
  key060: "请输入0以上范围的最低金额",
  key061: "请填写有效期",
  key062: "请确认日期",
  key063: "如果选择类目为ALL, 无法排除折扣商品",
  key064: "打折期间内有多次重复",
  key065: "折扣登记已完成",
  key066: "号码已重复",
  key067: "折扣信息获取失败",
  key068: "请选择活动或非活动",
  key069: "折扣信息已更新",
  key070: "用户信息读取失败",
  key071: "获取积分信息失败",
  key072: "获取优惠券信息失败",
  key073: "获取产品信息失败",
  key074: "获取订单信息失败",
  key075: "所选文件有问题",
  key076: "请仅输入电话号码",
  key077: "请输入收件人地址",
  key078: "请确认付款状态",
  key079: "请登录",
  key080: "请输入数字金额",
  key081: "该产品不属于库存管理范围",
  key082: "请确认库存数量",
  key083: "产品数量条件为全部时才有效",
  key084: "不能使用负数",

  key085: "请输入您的优惠券或积分",
  key086: "请仅输入分数的数字",
  key087: "积分从100点起可使用",
  key088: "请检查可用积分",
  key089: "积分只能应用一次",
  key090: "优惠券只能使用一次",
  key091: "请输入优惠券",
  key092: "不能使用生日优惠券",
  key093: "该优惠券已过期",
  key094: "此优惠券不可与促销同时使用",
  key095: "已超出优惠券兑换限额",
  key096: "查询优惠券历史信息失败\n请联系管理员",
  key097: "保存文件失败",
  key098: "代码注册成功",
  key099: "优惠券已注册",
  key100: "优惠券已被删除",
  key101: "优惠券已编辑", 
  key102: "图片上传成功",
  key103: "图片删除成功",
  key104: "图片删除失败",
  key105: "此优惠券仅限指定用户使用",
  key106: "这是未注册的优惠券",
  key107: "没有可以使用优惠券的类别或产品",
  key108: "需要代码",
  key109: "值1为必填项",
  key110: "这是一个注册代码",
  key111: "如果是类别 ALL,则无法选择产品",
  key112: "请输入4个字符的优惠券代码",
  key113: "请输入销售类型",
  key114: "销售代码已被注册",
  key115: "请输入优惠券类型",
  key116: "需要有有效期",  
  key117: "不能使用过去的日期",
  key118: "邮件设置时间已过去",
  key119: "请检查输入的日期",
  key120: "请输入2位数字的计数",
  key121: "请仅输入数字进行计数",
  key122: "请仅输入正数作为计数",
  key123: "期间内存在同种优惠券",
  key124: "优惠券代码有重复",
  key125: "图片为必填项",
  key126: "只能注册一张图像\n单击要删除的图像即可将其删除",
  key127: "图片已注册",
  key128: "请检查数量",
  key129: "再次检查您的帐户或密码",
}